language: python
python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cflow

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install matplotlib
  - pip install networkx
  - pip install django
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
  - coverage run setup.py test

after_success:
  - coveralls